spring:
  datasource:
    url: jdbc:mysql://localhost/db_cards
    username: root
    password: example
    driver-class-name: com.mysql.jdbc.Driver

database:
  url: jdbc:mysql://localhost:3306/db_cards
  username: root
  password: example
